In [1]:
print("코드 셀입니다.")

코드 셀입니다.


Markdown 셀입니다.

### 패키지 설치

In [2]:
!pip install numpy
!pip install pandas

^C


### 패키지 불러오기

In [3]:
import numpy as np
import pandas as pd

### 작업 공간 설정

In [ ]:
import os

# 확인
print(os.getcwd())

# 변경
os.chdir("c:/Users/A/OneDrive/바탕 화면/RA/Python Code")

C:\Users\A\Desktop


### 데이터 구조

In [ ]:
### 문자열 및 리스트

x = [1, 2, 3]
season = ["봄", "여름", "가을"]
print(type(x))         # <class 'list'>
print(type(season[0])) # <class 'str'>

<class 'list'>
<class 'str'>


In [ ]:
### 숫자 데이터 종류

x = np.array([1, 2, 3.0])
print(x.dtype)  # float64

x = np.array(["a", "b"])
print(x.dtype)  # <U1 (유니코드 문자열)

x = np.array([True, False])
print(x.dtype)  # bool

x = np.array([3 + 2j])
print(x.dtype)  # complex128

float64
<U1
bool
complex128


In [ ]:
### 데이터 형변환

x = np.array([1.2, 2.3])
x = x.astype(int)  # float → int

print(x)

[1 2]


In [ ]:
### Array 다루기

A = np.array([[1, 2, 3, 4, 5],
              [6, 7, 8, 9, 10]])
print(A[0])        # 첫 번째 행
print(A[:, 0])     # 첫 번째 열

B = np.array(range(1, 13)).reshape(2, 3, 2)  # 3차원 배열
print(B)

[1 2 3 4 5]
[1 6]
[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


In [ ]:
### Dictionary 다루기

person = {
    "name": "홍길동",
    "gender": "M",
    "score": [70, 80]
}

# 중첩 리스트
students = [
    {"name": "A", "gender": "M", "score": [70, 80]},
    {"name": "B", "gender": "F", "score": [60, 70]}
]

In [ ]:
### 범주형 자료

gender = pd.Series(["M", "F", "M"], dtype="category")
gender = gender.cat.set_categories(["F", "M"])

In [ ]:
### 데이터프레임

data = {
    "name": ["A", "B", "C"],
    "gender": ["M", "F", "M"],
    "height": [170, 165, 180],
    "score": [80, 95, 91]
}
df = pd.DataFrame(data)
print(df)

  name gender  height  score
0    A      M     170     80
1    B      F     165     95
2    C      M     180     91


In [11]:
df['name']        # Series 형태 반환

0    A
1    B
2    C
Name: name, dtype: object

In [ ]:
df[['name', 'score']]   # DataFrame 형태 반환

name  score
0    A     80
1    B     95
2    C     91

In [14]:
df.loc[2]               # 인덱스 라벨이 2인 행

name        C
gender      M
height    180
score      91
Name: 2, dtype: object

In [15]:
df.loc[0:2]             # 인덱스 라벨 0~2 범위의 행들

name gender  height  score
0    A      M     170     80
1    B      F     165     95
2    C      M     180     91

In [16]:
df.iloc[0]              # 첫 번째 행 (0번째 위치)

name        A
gender      M
height    170
score      80
Name: 0, dtype: object

In [17]:
df.iloc[0:3]            # 0~2번째 행들

name gender  height  score
0    A      M     170     80
1    B      F     165     95
2    C      M     180     91

In [18]:
df.loc[0, 'name']         # 라벨 기준: 0번째 행, 특정 열

'A'

In [19]:
df.iloc[0, 1]              # 위치 기준: 0번째 행, 1번째 열

'M'

In [20]:
df.loc[:, ['name', 'score']]   # 모든 행, 열1·열2만 선택

name  score
0    A     80
1    B     95
2    C     91

In [ ]:
### 함수 만들기

def area(x, y):
    return x * y

print(area(5, 6))  # 30

30


### 조건문

In [14]:
import random

x = random.random()
if x < 0.5:
    print("x는 0.5보다 작습니다")
elif x < 0.75:
    print("x는 0.75보다 작습니다")
else:
    print("x는 0.75 이상입니다")

x는 0.75보다 작습니다


### 반복문

In [15]:
for i in range(1, 5):
    print(i)

1
2
3
4


In [16]:
t = 0
sum_val = 0
while sum_val <= 100:
    t += 1
    sum_val += t
print(sum_val)

105


In [17]:
t = 0
sum_val = 0
while True:
    t += 1
    sum_val += t
    if sum_val > 100:
        break
print(sum_val)

105


### 데이터 다루기 실습

In [23]:
df = pd.read_csv("DataKoreaFrom200408To202306.csv")
df.head()

date   PI_CA   SI_CA   II_CA    PI_I    SI_I    II_I   PI_CO    SI_CO  \
0      td   5.000   5.000   5.000   5.000   5.000   5.000   5.000    5.000   
1  04-Aug  80.676  83.725  47.866  44.747  52.469  42.169  90.809   97.398   
2  04-Sep  83.572  84.319  48.542  44.970  52.976  42.437  92.941  103.601   
3  04-Oct  81.798  83.807  48.367  45.019  52.919  42.511  92.793  101.498   
4  04-Nov  82.503  84.153  49.361  45.883  53.771  44.000  95.844  106.127   

    II_CO  ...  KOSDAQ  Expected_inf  Oilprice  TB_spread  USCPI  IR_House  \
0   5.000  ...    5.00           2.0      5.00       2.00    5.0      2.00   
1  64.304  ...  355.66           3.4     44.94       0.60  189.2      5.80   
2  63.246  ...  362.08           3.3     45.95       0.64  189.8      5.63   
3  63.232  ...  357.04           3.3     53.13       0.57  190.8      5.57   
4  62.213  ...  373.43           3.3     48.46       0.62  191.7      5.47   

   USB_10  LeadingCI  LaggingCI  VKOSPI  
0    2.00        5.0        5.0    1.00  
1    4.28       56.6       59.8   22.76  
2    4.13       56.7       59.9   23.73  
3    4.10       56.9       60.1   27.17  
4    4.19       57.0       60.2   25.05  

[5 rows x 94 columns]

In [25]:
print(df.isnull().head())         # 각 값이 결측인지 확인

    date  PI_CA  SI_CA  II_CA   PI_I   SI_I   II_I  PI_CO  SI_CO  II_CO  ...  \
0  False  False  False  False  False  False  False  False  False  False  ...   
1  False  False  False  False  False  False  False  False  False  False  ...   
2  False  False  False  False  False  False  False  False  False  False  ...   
3  False  False  False  False  False  False  False  False  False  False  ...   
4  False  False  False  False  False  False  False  False  False  False  ...   

   KOSDAQ  Expected_inf  Oilprice  TB_spread  USCPI  IR_House  USB_10  \
0   False         False     False      False  False     False   False   
1   False         False     False      False  False     False   False   
2   False         False     False      False  False     False   False   
3   False         False     False      False  False     False   False   
4   False         False     False      False  False     False   False   

   LeadingCI  LaggingCI  VKOSPI  
0      False      False   False  
1      False

In [26]:
print(df.isnull().sum())   # 각 열의 결측치 개수 확인

date         0
PI_CA        0
SI_CA        0
II_CA        0
PI_I         0
            ..
IR_House     0
USB_10       0
LeadingCI    0
LaggingCI    0
VKOSPI       0
Length: 94, dtype: int64


In [27]:
df_clean = df.dropna() # 결측치 제거

In [ ]:
# 필터 (filter)
setosa = df[df['KOSDAQ'] < 600]

# 선택 (select)
selected = df[['Oilprice', 'KOSDAQ']]

# 새 변수 만들기 (mutate)
df['USCPI'] = df['USCPI'] / df['KOSDAQ']

In [ ]:
!pip install openpyxl

In [ ]:
# CSV 파일로 저장
df.to_csv("저장결과.csv", index=False)

# Excel 파일 저장 (openpyxl 설치 필요)
df.to_excel("저장결과.xlsx", index=False)